server:
  port: 8083

grpc:
  client:
    refdata:
      address: ${GRPC_REF_DATA_ADDRESS}
      negotiationType: PLAINTEXT
    route:
      address: ${GRPC_ROUTE_ADDRESS}
      enableKeepAlive: true
      negotiationType: PLAINTEXT
    archive:
      address: ${GRPC_ARCHIVE_ADDRESS:dns:///localhost:8094}
      negotiationType: PLAINTEXT

spring:
  servlet:
    multipart:
      max-file-size: ${SPRING_MULTIPART_MAX_FILE_SIZE:50MB}
      max-request-size: ${SPRING_MULTIPART_MAX_REQUEST_SIZE:50MB}

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: prometheus,health
  metrics:
    export:
      prometheus:
        enabled: true
