server:
  port: 8083

grpc:
  client:
    refdata:
      address: ${GRPC_REF_DATA_ADDRESS}
      negotiationType: PLAINTEXT
    route:
      address: ${GRPC_ROUTE_ADDRESS}
      enableKeepAlive: true
      negotiationType: PLAINTEXT

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: prometheus,health
  metrics:
    export:
      prometheus:
        enabled: true